[environments]
  [environments.development]
    name = "japp"
    namespace = "japp-personal-dev"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
